apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sung
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sung
  template:
    metadata:
      labels:
        app: sung
    spec:
      containers:
      - name: sung
        image: luksa/kubia
